service: taskpulse-api

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ap-south-1

functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-offline